import './globals.css'

import type { Metadata } from 'next'
import { Archivo } from 'next/font/google'
import Script from 'next/script'

const archivo = Archivo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.className} bg-background bg-blur-gradient-mobile bg-cover sm:bg-blur-gradient`}
      >
        {children}
      </body>
      <Script>{`<script>document.documentElement.classList.add('js')</script>`}</Script>
      <Script src="https://unpkg.com/taos@1.0.5/dist/taos.js" />
    </html>
  )
}
